spring:
  application:
    name: user-service
  main:
    web-application-type: reactive
  datasource:
    url: ${USER_DB_POSTGRES_JDBC_URL}
    username: ${USER_DB_POSTGRES_USER}
    password: ${USER_DB_POSTGRES_PASSWORD}
  r2dbc:
    url: ${USER_DB_POSTGRES_R2DBC_URL}
    username: ${USER_DB_POSTGRES_USER}
    password: ${USER_DB_POSTGRES_PASSWORD}
  data:
    r2dbc:
      repositories:
        enabled: true
  flyway:
    enabled: true
    url: ${USER_DB_POSTGRES_JDBC_URL}
    user: ${USER_DB_POSTGRES_USER}
    password: ${USER_DB_POSTGRES_PASSWORD}
    locations: classpath:db/migration

okta:
  oauth2:
    issuer: ${ISSUER_URI}
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
    audience: ${ISSUER_URI}api/v2/

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}

super-admin:
  nickname: ${SUPER_ADMIN_NICKNAME}
  email: ${SUPER_ADMIN_EMAIL}
  auth0-user-id: ${SUPER_ADMIN_AUTH0_USER_ID}

regular-user:
  nickname: ${REGULAR_USER_NICKNAME}
  email: ${REGULAR_USER_EMAIL}
  auth0-user-id: ${REGULAR_USER_AUTH0_USER_ID}
